### ISSUE TITLE
Boolean Type causes error in play 1.0.3 using Siena Model

### ISSUE THREAD

**Issue by markellul** [lmcalpin/Play--Scaffold#1]
When using a Boolean entry in a model, and generating the scaffold the below error is thrown when running... using play 1.0.3 and siena.model

The template /app/views/ComplimentaryEntryTypes/create.html does not compile : unexpected token: & 

in /app/views/ComplimentaryEntryTypes/create.html (around line 57)
53:                                     food
54:                             </div>
55:             <div class="field">
56:                                     <input type="checkbox" name="entity.food"
57:                         ${entity?.food ? &quot;checked&quot;:&quot;&quot;}                  />
58:                                                     </div>
59:         <span class="error">${errors.forKey('entity.food')}</span>
60:     </div>
61:         <input type="submit" name="submit" value="Save" />
62: #{/form}
63: </div>

**Comment by lmcalpin** [comment]
recreated the problem and checked in a fix to the generateExpression tag
thanks for reporting this!
